uploads = []
outputs = []

[[generated]]
id = "wM4YVMwwTFxAjz5vD_OvU"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "oqKTxeTan4zWFr--qqNKl"
uri = "file://artifacts/mobile/assets/images/splash-icon.png"
type = "image"
title = "generated_image"
